#!/bin/bash

function curlInstall(){
  echo "1"
}

if [ `curlInstall`"_" = "1_" ]
then
  echo "check env, curl is installed"
else
  echo "sorry you need install curl first"
  exit
fi


cd /tmp
rm -rf marmot
echo "get the tool from https://raw.githubusercontent.com/shishengyi/Marmot/master/app/marmot"
curl "https://raw.githubusercontent.com/shishengyi/Marmot/master/app/marmot" > marmot
chmod +x marmot

if [ -f "/usr/local/bin/marmot" ]
then
  if [ $1_ != "update_" ]
  then
    echo "the /usr/local/bin/marmot exist, maybe you have install one"
    echo "if you want to update this file, use base installmarmot update"
    exit
  else
    rm -rf /usr/local/bin/marmot
  fi
fi

cp marmot /usr/local/bin/marmot
chmod +x /usr/local/bin/marmot

echo "the marmot install success, have fun"
