#!/bin/bash

export MARMOT_GITHUB="https://github.com/shishengyi/Marmot"
export MARMOT_TOOLSURL="https://raw.githubusercontent.com/shishengyi/Marmot/master/tools/"

function getCurUserDir(){
  echo "/Users/"$USER"/marmot";
}
export MARMOT_PATH=`getCurUserDir`
export MARMOT_PATH_TOOLS=${MARMOT_PATH}"/tools"

function doctor(){
  curdir=$(getCurUserDir)"/marmot/tools"
  if [ ! -d ${curdir} ]
  then
    mkdir -p ${curdir}
  fi
}

function curlInstall(){
  echo "1"
}
export MARMOT_CURLINSTALL=`curlInstall`

function commandNotFound(){
  echo "Command $1 can not found at:"
  echo ${MARMOT_PATH}"/marmot/tools/"$1
  echo ${MARMOT_PATH}"/marmot/tools/"$1".sh"
  echo "may be you should call \"marmot install $1\" at first"
}

function run(){
  runfile=$(getCurUserDir)"/marmot/tools/"$1
  if [ ! -f ${runfile} ];then
    runfile=$(getCurUserDir)"/marmot/tools/"$1".sh";
    if [ ! -f ${runfile} ];then
      commandNotFound $1
      exit
    fi
  fi

  shift
  bash ${runfile} $*
}

function checkUrlAndDownload(){
  url=$1
  filename=$2
  echo "check url : ${url}"
  httpCode=`curl -o /dev/null -s -w %{http_code} ${url}`
  if [ ${httpCode}"_" = "200_" ]
  then
    echo "check ok, begin downing..."
    curl ${url} > ${filename}
    return 0
  else
    echo "failure,the http code : "${httpCode}
    return 1
  fi
}

function install(){
  if [ -f ${MARMOT_PATH_TOOLS}"/"$1 ]
  then
    echo ${MARMOT_PATH_TOOLS}"/"$1" existed, install success"
    echo "if you want to update the tool, please run \"marmot update $1\""
    exit
  fi

  if [ ${MARMOT_CURLINSTALL}"_" = "1_" ]
  then
    cd /tmp
    rm -rf $1

    url=${MARMOT_TOOLSURL}$1
    checkUrlAndDownload ${url} $1
    if [ $? != 0 ]
    then
      url=${url}".sh"
      checkUrlAndDownload ${url} $1
      if [ $? != 0 ]
      then
        echo "exit install, install failure!!"
        exit
      fi
    fi

    if [ ! -f "/tmp/"$1 ]
    then
      echo "download file failure, install failure"
      exit 1
    fi

    echo "set execute property"
    chmod +x "/tmp/"$1

    echo "copy the file to ${MARMOT_PATH_TOOLS}"
    cp "/tmp/"$1 "${MARMOT_PATH_TOOLS}/$1"

    echo "$1 installed success"
  else
    echo "install need install curl first"
  fi
}

function help(){
  echo "======== ############################################ ========"
  echo "======== welcome to marmot tools,I am a tools manager ========"
  echo "======== ############################################ ========"
  echo "I can install/uninstall/update/run tools,the tools is from ${MARMOT_GITHUB}"
  echo "for example:"
  echo "marmot install removefile : install a tool named removefile from ${MARMOT_TOOLSURL}, this shell will copy to ${MARMOT_PATH_TOOLS}"
  echo "marmot uninstall removefile : the file ${MARMOT_PATH_TOOLS}/removefile.sh will be delete"
  echo "marmot update removefile : just like marmot uninstall removefile && marmot install removefile"
  echo "marmot removefile : execute ${MARMOT_PATH_TOOLS}/removefile.sh"
  echo "for more information, visit ${MARMOT_GITHUB}"
  echo "Have a good fun"
}

doctor

if [ $# = 0 ]
then
  help
  exit 0
fi

case $1 in
  install)
    shift
    install $*
    ;;
  run)
    shift
    run $*
    ;;
  help)
    help
    ;;
  *)
    run $*
    ;;
esac
