#!/bin/bash

export MARMOT_GITHUB="https://github.com/shishengyi/Marmot"
export MARMOT_TOOLSURL="https://raw.githubusercontent.com/shishengyi/Marmot/master/tools/"

function getCurUserDir(){
  echo "/Users/"$USER"/marmot";
}
export MARMOT_PATH=`getCurUserDir`
export MARMOT_PATH_TOOLS=${MARMOT_PATH}"/tools"

function doctor(){
  curdir=$(getCurUserDir)"/marmot/tools"
  if [ ! -d ${curdir} ]
  then
    mkdir -p ${curdir}
  fi
}

function curlInstall(){
  echo "1"
}
export MARMOT_CURLINSTALL=`curlInstall`

function commandNotFound(){
  echo "Command $1 can not found at:"
  echo ${MARMOT_PATH}"/marmot/tools/"$1
  echo ${MARMOT_PATH}"/marmot/tools/"$1".sh"
  echo "may be you should call \"marmot install $1\" at first"
}

function run(){
  runfile=$(getCurUserDir)"/marmot/tools/"$1
  if [ ! -f ${runfile} ];then
    runfile=$(getCurUserDir)"/marmot/tools/"$1".sh";
    if [ ! -f ${runfile} ];then
      commandNotFound $1
      exit
    fi
  fi

  shift
  bash ${runfile} $*
}

function help(){
  echo "======== ############################################ ========"
  echo "======== welcome to marmot tools,I am a tools manager ========"
  echo "======== ############################################ ========"
  echo "I can install/uninstall/update/run tools,the tools is from ${MARMOT_GITHUB}"
  echo "for example:"
  echo "marmot install removefile : install a tool named removefile from ${MARMOT_TOOLSURL}, this shell will copy to ${MARMOT_PATH_TOOLS}"
  echo "marmot uninstall removefile : the file ${MARMOT_PATH_TOOLS}/removefile.sh will be delete"
  echo "marmot update removefile : just like marmot uninstall removefile && marmot install removefile"
  echo "marmot removefile : execute ${MARMOT_PATH_TOOLS}/removefile.sh"
  echo "for more information, visit ${MARMOT_GITHUB}"
  echo "Have a good fun"
}

doctor

if [ $# = 0 ]
then
  help
  exit 0
fi

case $1 in
  install)
    shift
    bash install $*
    ;;
  run)
    shift
    run $*
    ;;
  help)
    help
    ;;
  *)
    run $*
    ;;
esac
